### PR TITLE
[WIP] Fix issues from infer run

### LINKED ISSUE #1297: Infer run on nd4j reveals a few possible issues
As a fun exercise I've run [Facebook's infer](http://fbinfer.com/) on c53591a3301daa60f4c5d6de2c15ca5f94e38a9a Here's the output:

```
Analyzed 364 files

Found 35 issues

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java:2754: error: NULL_DEREFERENCE
  object returned by getBlasWrapper().level3() could be null and is dereferenced at line 2754
  2752.               else {
  2753.                   Nd4j.getBlasWrapper().level3().gemm(
  2754. >                         BlasBufferUtil.getCharForTranspose(result)
  2755.                           ,BlasBufferUtil.getCharForTranspose(this)
  2756.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java:3862: error: NULL_DEREFERENCE
  object shape last assigned on line 3859 could be null and is dereferenced by call to create(...) at line 3862
  3860.           if(indexes[0] instanceof SpecifiedIndex) {
  3861.               INDArray ret = create(shape);
  3862. >             int count = 0;
  3863.               if(isVector()) {
  3864.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/compression/CompressedDataBuffer.java:104: error: RESOURCE_LEAK
   resource of type org.bytedeco.javacpp.BytePointer acquired by call to new() at line 96 is not released after line 104
  102.                   CompressedDataBuffer compressedBuffer = new CompressedDataBuffer(pointer, descriptor);
  103.                   return Nd4j.getCompressor().decompress(compressedBuffer);
  104. > 
  105.               } catch (Exception e) {
  106.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/MiniBatchFileDataSetIterator.java:204: error: RESOURCE_LEAK
   resource of type java.io.FileOutputStream acquired by call to FileOutputStream(...) at line 190 is not released after line 204
  202.           ret[0] = new File(rootDir,dataSetId + ".bin").getAbsolutePath();
  203.           ret[1] = new File(rootDir,dataSetId + ".labels.bin").getAbsolutePath();
  204. >         return ret;
  205.   
  206.       }
  207.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/api/iterator/cache/InFileAndMemoryDataSetCache.java:52: error: NULL_DEREFERENCE
  object dataSet last assigned on line 50 could be null and is dereferenced by call to put(...) at line 52
  50.               dataSet = fileCache.get(key);
  51.               if (!memoryCache.contains(key)) {
  52. >                 memoryCache.put(key, dataSet);
  53.               }
  54.           }
  55.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/api/preprocessor/NormalizerStandardize.java:129: error: NULL_DEREFERENCE
  object NormalizerStandardize.featureMeanStd last assigned on line 117 could be null and is dereferenced at line 129
  127.               if(featureMeanStd == null) {
  128.                   this.fit(next);
  129. >                 featureMeanStd.getRow(1).muli(batchCount);
  130.                   if (fitLabels) {
  131.                       labelMeanStd.getRow(1).muli(batchCount);
  132.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/api/preprocessor/NormalizerStandardize.java:147: error: NULL_DEREFERENCE
  object NormalizerStandardize.featureMeanStd last assigned on line 117 could be null and is dereferenced by call to runnningFit(...) at line 147
  145.               }
  146.           }
  147. >         this.runnningFit(featureMeanStd,featureMeanStd,batchCount,runningTotal,true);
  148.           featureMean = featureMeanStd.getRow(0).dup();
  149.           featureStd = featureMeanStd.getRow(1).dup();
  150.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:51: error: NULL_DEREFERENCE
  object returned by level1() could be null and is dereferenced at line 51
  49.   //            throw new IllegalArgumentException("Unable to use axpy on a non vector");
  50.           LinAlgExceptions.assertSameLength(dx,dy);
  51. >         level1().axpy(dx.length(),da.doubleValue(),dx,dy);
  52.           return dy;
  53.       }
  54.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:66: error: NULL_DEREFERENCE
  object returned by level2() could be null and is dereferenced at line 66
  64.           LinAlgExceptions.assertVector(x, y);
  65.           LinAlgExceptions.assertMatrix(a);
  66. >         level2().gemv(BlasBufferUtil.getCharForTranspose(a),BlasBufferUtil.getCharForTranspose(x),alpha.doubleValue(),a,x,beta,y);
  67.           return y;
  68.       }
  69.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:72: error: NULL_DEREFERENCE
  object returned by level2() could be null and is dereferenced at line 72
  70.       @Override
  71.       public INDArray ger(Number alpha, INDArray x, INDArray y, INDArray a) {
  72. >         level2().ger(BlasBufferUtil.getCharForTranspose(x),alpha.doubleValue(),x,y,a);
  73.           return a;
  74.       }
  75.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:86: error: NULL_DEREFERENCE
  object returned by level2() could be null and is dereferenced at line 86
  84.       @Override
  85.       public IComplexNDArray geru(IComplexNumber alpha, IComplexNDArray x, IComplexNDArray y, IComplexNDArray a) {
  86. >         level2().geru('N',alpha,x,y,a);
  87.           return a;
  88.       }
  89.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:98: error: NULL_DEREFERENCE
  object returned by level1() could be null and is dereferenced at line 98
  96.       @Override
  97.       public INDArray swap(INDArray x, INDArray y) {
  98. >         level1().swap(x,y);
  99.           return y;
  100.       }
  101.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:108: error: NULL_DEREFERENCE
  object returned by level1() could be null and is dereferenced at line 108
  106.           if(x.data().dataType() == DataBuffer.Type.FLOAT)
  107.               return scal((float) alpha,x);
  108. >         level1().scal(x.length(),alpha,x);
  109.           return x;
  110.       }
  111.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:118: error: NULL_DEREFERENCE
  object returned by level1() could be null and is dereferenced at line 118
  116.           if(x.data().dataType() == DataBuffer.Type.DOUBLE)
  117.               return scal((double) alpha,x);
  118. >         level1().scal(x.length(),alpha,x);
  119.           return x;
  120.       }
  121.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:145: error: NULL_DEREFERENCE
  object returned by level1() could be null and is dereferenced at line 145
  143.       public INDArray copy(INDArray x, INDArray y) {
  144.           LinAlgExceptions.assertVector(x,y);
  145. >         level1().copy(x,y);
  146.           return y;
  147.       }
  148.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:152: error: NULL_DEREFERENCE
  object returned by level1() could be null and is dereferenced at line 152
  150.       public IComplexNDArray copy(IComplexNDArray x, IComplexNDArray y) {
  151.           LinAlgExceptions.assertVector(x,y);
  152. >         level1().copy(x,y);
  153.           return y;
  154.       }
  155.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:162: error: NULL_DEREFERENCE
  object returned by level1() could be null and is dereferenced at line 162
  160.           if(dx.data().dataType() == DataBuffer.Type.FLOAT)
  161.               return axpy((float) da,dx,dy);
  162. >         level1().axpy(dx.length(),da,dx,dy);
  163.           return dy;
  164.       }
  165.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:173: error: NULL_DEREFERENCE
  object returned by level1() could be null and is dereferenced at line 173
  171.               return axpy((double) da,dx,dy);
  172.   
  173. >         level1().axpy(dx.length(),da,dx,dy);
  174.           return dy;
  175.       }
  176.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:188: error: NULL_DEREFERENCE
  object returned by level1() could be null and is dereferenced at line 188
  186.       @Override
  187.       public double dot(INDArray x, INDArray y) {
  188. >         return level1().dot(x.length(),1,x,y);
  189.       }
  190.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:194: error: NULL_DEREFERENCE
  object returned by level1() could be null and is dereferenced at line 194
  192.       public IComplexNumber dotc(IComplexNDArray x, IComplexNDArray y) {
  193.           LinAlgExceptions.assertVector(x,y);
  194. >         return level1().dot(x.length(),Nd4j.UNIT,x,y);
  195.       }
  196.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:200: error: NULL_DEREFERENCE
  object returned by level1() could be null and is dereferenced at line 200
  198.       public IComplexNumber dotu(IComplexNDArray x, IComplexNDArray y) {
  199.           LinAlgExceptions.assertVector(x,y);
  200. >         return level1().dot(x.length(),Nd4j.UNIT,x,y);
  201.       }
  202.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:206: error: NULL_DEREFERENCE
  object returned by level1() could be null and is dereferenced at line 206
  204.       public double nrm2(INDArray x) {
  205.           LinAlgExceptions.assertVector(x);
  206. >         return level1().nrm2(x);
  207.       }
  208.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:219: error: NULL_DEREFERENCE
  object returned by level1() could be null and is dereferenced at line 219
  217.       public double asum(INDArray x) {
  218.           LinAlgExceptions.assertVector(x);
  219. >         return level1().asum(x);
  220.       }
  221.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:231: error: NULL_DEREFERENCE
  object returned by level1() could be null and is dereferenced at line 231
  229.       @Override
  230.       public int iamax(INDArray x) {
  231. >         return level1().iamax(x);
  232.       }
  233.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:248: error: NULL_DEREFERENCE
  object returned by level2() could be null and is dereferenced at line 248
  246.               return gemv((float) alpha,a,x,(float) beta,y);
  247.           }
  248. >         level2().gemv('N','N',alpha,a,x,beta,y);
  249.           return y;
  250.       }
  251.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:260: error: NULL_DEREFERENCE
  object returned by level2() could be null and is dereferenced at line 260
  258.               return gemv((double) alpha,a,x,(double) beta,y);
  259.           }
  260. >         level2().gemv('N','N',alpha,a,x,beta,y);
  261.           return y;
  262.       }
  263.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:273: error: NULL_DEREFERENCE
  object returned by level2() could be null and is dereferenced at line 273
  271.           }
  272.   
  273. >         level2().ger('N',alpha,x,y,a);
  274.           return a;
  275.       }
  276.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:287: error: NULL_DEREFERENCE
  object returned by level2() could be null and is dereferenced at line 287
  285.           }
  286.   
  287. >         level2().ger('N',alpha,x,y,a);
  288.           return a;
  289.       }
  290.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:369: error: NULL_DEREFERENCE
  object returned by level3() could be null and is dereferenced at line 369
  367.           level3().gemm(
  368.                   BlasBufferUtil.getCharForTranspose(a),
  369. >                 BlasBufferUtil.getCharForTranspose(b)
  370.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:389: error: NULL_DEREFERENCE
  object returned by level3() could be null and is dereferenced at line 389
  387.           }
  388.   
  389. >         level3().gemm(
  390.                   BlasBufferUtil.getCharForTranspose(a),
  391.                   BlasBufferUtil.getCharForTranspose(b)
  392.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseBlasWrapper.java:405: error: NULL_DEREFERENCE
  object returned by level3() could be null and is dereferenced at line 405
  403.           LinAlgExceptions.assertMatrix(a,b,c);
  404.   
  405. >         level3().gemm(
  406.                   BlasBufferUtil.getCharForTranspose(a),
  407.                   BlasBufferUtil.getCharForTranspose(b)
  408.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java:806: error: NULL_DEREFERENCE
  object returned by getBlasWrapper().level3() could be null and is dereferenced at line 806
  804.        */
  805.       public static INDArray gemm(INDArray a, INDArray b, INDArray c, boolean transposeA, boolean transposeB, double alpha, double beta ){
  806. >         getBlasWrapper().level3().gemm(a,b,c,transposeA,transposeB,alpha,beta);
  807.           return c;
  808.       }
  809.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java:2292: error: RESOURCE_LEAK
   resource of type java.io.FileOutputStream acquired by call to FileOutputStream(...) at line 2286 is not released after line 2292
  2290.           dos.close();
  2291.   
  2292. >     }
  2293.   

nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java:5200: error: NULL_DEREFERENCE
  object returned by getProperty("java.vm.name") could be null and is dereferenced at line 5200
  5198.               }
  5199.   
  5200. >             if (!System.getProperty("java.vm.name").equalsIgnoreCase("Dalvik")
  5201.                       && !System.getProperty("os.arch").toLowerCase().startsWith("arm")
  5202.                       && !System.getProperty("sun.arch.data.model").equals("64")) {
  5203.   

nd4j-backends/nd4j-api-parent/nd4j-native-api/src/main/java/org/nd4j/compression/impl/Gzip.java:84: error: RESOURCE_LEAK
   resource of type org.apache.commons.io.output.ByteArrayOutputStream acquired to stream by call to new() at line 67 is not released after line 84
  82.               return result;
  83.           } catch (Exception e) {
  84. >             throw new RuntimeException(e);
  85.           }
  86.   

Summary of the reports

  NULL_DEREFERENCE: 31
     RESOURCE_LEAK: 4
```

### PR DESCRIPTION
**Pull request by huitseeker**
Fixes #1297.

Among places underlines by infer, one of the common patterns is 

```
BufferedOutputStream bs = ...
DataOutputStream dos = new DataOutputStream(dos);
<do stg with dos>
dos.close();
```

[Infer](https://github.com/facebook/infer), in this case, reports the innermost resource as un-closed even though in most situations the flush & close of the outermost resource does close the innermost. That's because an exception during the flush of one of the outer streams will leave any stream constructed by the nested calls inside it open.

I did not address those cases because a consistent tackling of this issue would most likely be a codebase-wide refactor to `try .. with` construct (ideally tool-powered).

Suggested reviewer @raver119

### CODE REVIEW

File: nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/compression/CompressedDataBuffer.java [hunk 1]
```diff
@@ -93,15 +93,16 @@ public static DataBuffer readUnknown(DataInputStream s, long length) {
...
-                CompressionDescriptor descriptor = new CompressionDescriptor();
-                descriptor.setCompressedLength(compressedLength);
-                descriptor.setCompressionAlgorithm(compressionAlgorithm);
-                descriptor.setOriginalLength(originalLength);
-                descriptor.setNumberOfElements(numberOfElements);
-
-                CompressedDataBuffer compressedBuffer = new CompressedDataBuffer(pointer, descriptor);
-                return Nd4j.getCompressor().decompress(compressedBuffer);
+                try(Pointer pointer = new BytePointer(temp)){
+                    CompressionDescriptor descriptor = new CompressionDescriptor();
```
Comment (agibsonccc) [inline nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/compression/CompressedDataBuffer.java]: Pointers should be auto collected with javacpp.

**Comment by agibsonccc** [comment]
Agree with most things here. The try with on the pointer should be taken care of by javacpp though /cc @saudet

File: nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/compression/CompressedDataBuffer.java (hunk 1 above)
Comment (saudet) [inline nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/compression/CompressedDataBuffer.java]: Not a bad idea if we know we won't need it though.

**Comment by huitseeker** [comment]
This is kind of blocked by #1312 (and fix #1317 is not merged).

**Comment by huitseeker** [comment]
somebody should probably kick another build of this one if tests pass now /cc @raver119 @eraly

**Comment by raver119** [comment]
start jenkins
